### ISSUE TITLE
Flattening

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc-csv#1]
Would it be possible to make flattening implicit when converting to CSV? Wasn't the edge case you fixed in flattening over on the twarc v2 branch about making flattening a no-op if data was already flat?

If users have already flattened their data and don't want to incur the expense of re-flattening they could pass a --noflat option?

**Comment by edsu** [comment]
Also, I like the use of pandas to simplify things! It is a pretty chunky dependency, but I imagine most people using Python to analyze tweets will not mind. This will possibly result in the format changing over time, but I don't see anyway around that.

**Comment by igorbrigadir** [comment]
Yep - that's exactly it, i just didn't get time to add the code to check for already flat data or call flatten if it's not yet flattened.

For `--noflat` I thought we could check to see if it's a newline delimited json, or a json response object by reading the first line of the file, and we can skip that check with that flag too.

I'm also ok with pandas as a dependency for now, for the exact same reasons.

The format that it ends up with right now is "opinionated" because that's how i decided to go with it, but i'd like to add a bunch of optional flags or configs to allow people to do things differently if they need (do or don't inline referenced tweets, subset columns or pass specific arguments to the to_csv command which is sometimes needed).

Another thing i just thought of: 

We can output to anything pandas can output - so maybe an option for parquet or gzipped pickle is worth adding too? I know the plugin is "CSV" but i don't think it's too confusing to make it output another format of dataframe.

**Comment by edsu** [comment]
That's actually a great idea about parquet and pickle, and I think you're right twarc-csv is a good hook for anyone looking to work with collected data as a data frame.

**Comment by edsu** [comment]
I've added the ability to also work with unflattened data. It's a bit more verbose, but hopefully it's understandable.

**Comment by edsu** [comment]
Could we get a v0.0.2 release on PyPI?
