### ISSUE TITLE
Error skipping batch of tweets

### ISSUE THREAD

**Issue by luisignaciomenendez** [DocNow/twarc-csv#13]
I am facing some problems with the twarc2 csv  command. I am using it to convert a (large) json file as follows:
`twarc2 csv treatment.json treatment.csv`
When the progress bar reaches about 89% it returns the error:
```
 "withheld.scope"
 to fix, add these with --input-columns. Skipping entire batch of 670325 tweets!
```
Now I assumed that this means I need to add that option to the command line in order to recover those tweets. I am doing it like this :
` twarc2 csv --input-columns "withheld.scope" treatment.json treatment.csv ` 

but it returns an error again.  I have updated twarc to its last version and the code alwys worked properly to me but in this file.

Thanks in advance!

**Comment by igorbrigadir** [comment]
> Skipping entire batch of 670325 tweets!

This is odd because with the default batch size, this number shouldn't be that large, did the giant json come from some other process or was it directly from a `twarc2` command? If so, what was the command / process?

Is it the exact same error after you specify `--input-columns "withheld.scope"` or a different error?

It would be great to try and extract this tweet as an example. I was having trouble finding examples of different "withheld" tweets

**Comment by edsu** [comment]
I see `witheld.scope` was added to the list of columns. @igorbrigadir should we release this for @luisignaciomenendez to try?

**Comment by igorbrigadir** [comment]
I did spot a bug where i wasn't checking for the differences properly and fixed it, and the number of results in a batch are actually ok here - i may have set the default batch size a bit too large though, so i reduced that too. This has the effect of making more frequent writes.

update with:

```
pip3 install --upgrade twarc-csv
```

and run

```
twarc2 csv treatment.json treatment.csv
```

again.

I got the example tweets you sent and it's working on that, so feel free to reopen if there are more errors!
